### ISSUE TITLE
Prestashop 1.7.x Template not found

### ISSUE THREAD

**Issue by hknyldz** [L3o-pold/prestashopamp#1]
when I installed this module, i show 500 internet server error. for example: https://hobinoktasi.com/module/amp/product?idProduct=494

**Comment by L3o-pold** [comment]
I will need some errors log to see what's happening.
Change your config /defines.inc.php
`define('_PS_MODE_DEV_', false);`

to

`define('_PS_MODE_DEV_', true);`

Or check your Apache logs

**Comment by hknyldz** [comment]
here in logs
http://paste.linuxturkey.org/?bd9c5349e2ed21b7#Q0q8s16tjpzQTgQ3bM+BCnJenNIhJWPy25Gz5E6mjTA=

**Comment by L3o-pold** [comment]
It seems like an issue on your side. Could you activate the logs from the config/defines.inc.php file maybe it'll be more explicit.

**Comment by hknyldz** [comment]
here in front logs
http://paste.linuxturkey.org/?30cb967e48e15aa0#r52Vn/XBNesCYiI17GabcVrQDzv+xH2XVGYrsu/1CNg=

**Comment by L3o-pold** [comment]
The module can't find the template, what is your version of Prestashop and the AMP module?

**Comment by hknyldz** [comment]
prestashop 1.7.2.4 amp 2.0.1

**Comment by L3o-pold** [comment]
Ok, so it's normal, the module is actually working only on 1.6.x Prestashop version.
I will add a note on the README.

It should not be long to handle 1.7 so I will look on it very soon.

**Comment by hknyldz** [comment]
okey thanks. I'm waiting. Thanks for your help

**Comment by L3o-pold** [comment]
A new version that's supporting Prestashop 1.7.x is released

https://github.com/L3o-pold/prestashopamp/releases/download/2.0.5/amp.zip
