### ISSUE TITLE
Pages not working with PS facebook Pixel

### ISSUE THREAD

**Issue by Utopia69** [L3o-pold/prestashopamp#10]
Hi,
The amp pages are not working when you enable the module "Official Pixel Facebook Module"
https://addons.prestashop.com/en/products-on-facebook-social-networks/27646-official-pixel-facebook.html 
Anybody knows a fix?
Grtz,

**Comment by L3o-pold** [comment]
Duplicate with #6 please update your module.

**Comment by Utopia69** [comment]
whoops, missed this one
works now
