### ISSUE TITLE
no settings possible after installation with PS 1.7.4.4

### ISSUE THREAD

**Issue by didi-2018** [L3o-pold/prestashopamp#11]
Hi, I just installed your latest version v2.0.14 in PS 1.7.4.4 and there is no Button for settings. Only for "deinstall" "disable mobil" and "reset". 

![image](https://user-images.githubusercontent.com/44971218/52535061-01a60c80-2d4a-11e9-9a48-9863bdbd55c9.png)

What should I do to make it work? 

Thank you very much in advance for your answer.

**Comment by L3o-pold** [comment]
Hi,
If the module is installed and activated you have nothing more to do. 
It will automaticaly create AMP pages
