### ISSUE TITLE
can't surclass module in theme

### ISSUE THREAD

**Issue by yoanmarchal** [L3o-pold/prestashopamp#13]
css is not loaded from theme/modules/amp/views/css/amp.css

**Comment by L3o-pold** [comment]
Prestashop 1.7.x?

**Comment by yoanmarchal** [comment]
prestashop 1.6.1.24

**Comment by L3o-pold** [comment]
Fixed in the latest release: https://github.com/L3o-pold/prestashopamp/releases/tag/2.0.18
