### ISSUE TITLE
various error: xml:lang

### ISSUE THREAD

**Issue by ourssauvage** [L3o-pold/prestashopamp#14]
Many thanks for your plugin.
I ve some errors with the amp validator and google AMP validator, on three product category pages in the English language.
The basic language of my shop is French

i'm on prestashop 1.7.6.1

The attribute 'xml:lang' may not appear in tag 'span'
line 157, column 7
The attribute 'xml:lang' may not appear in tag 'span'
line 158, column 7
The attribute 'xml:lang' may not appear in tag 'span'
line 157, column 7

I did not find or fix that manually.

thanks in advance

**Comment by L3o-pold** [comment]
Is a still happening?

**Comment by L3o-pold** [comment]
Fixed in https://github.com/L3o-pold/prestashopamp/releases/tag/2.0.20

**Comment by ourssauvage** [comment]
sorry. I found the error.
While searching, I found html xml: lang code in the html code of some of my product sheets.
By removing the code there are no more errors.
