### ISSUE TITLE
AMP error when product or category description contains style attribute

### ISSUE THREAD

**Issue by hknyldz** [L3o-pold/prestashopamp#2]
"style amp-custom" tag CSS errors - invalid notification.

"style amp-custom" tag CSS error - incomplete notification.

The inline 'style' attribute is not allowed in AMP documents, use 'style amp-custom' tag instead

**Comment by L3o-pold** [comment]
Did you customize the module template?

**Comment by hknyldz** [comment]
I didn't. Do i need ?

**Comment by L3o-pold** [comment]
No you don't. Could you provide me the URL you are testing at leopold.jacquot[at]gmail.com ?

**Comment by hknyldz** [comment]
I sent mail.

**Comment by L3o-pold** [comment]
Thank you, I think the problem is the HTML in the category description, I will release a fix in the next minutes.
An other problem is that your product description contains style tag and that's not allowed in AMP.

**Comment by L3o-pold** [comment]
I deployed a new release, but it will not fix the fact that you have style attribute in the HTML of your product description or your category description.

One fix on your side is to override the module theme and remove the HTML from your description with a strip_tags modifier: https://www.smarty.net/docsv2/en/language.modifier.strip.tags.tpl

Or if it's a recrurent problem for every user, I can do this on the module side, so it'll prevent any HTML on the user content, but I'm not sure it's the best for everyone.

**Comment by L3o-pold** [comment]
A new version is available (2.0.8) and should fix issues with style attribute in your HTML.

**Comment by p2rcoder** [comment]
Why module dont replace unused html in description itself? Should I now rewrite 10 000 description to be able to have AMP?

**Comment by L3o-pold** [comment]
No, that's why I released an update, it'll automatically remove style attribute from HTML.

**Comment by p2rcoder** [comment]
Cool!
