### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by omeco4christ** [L3o-pold/prestashopamp#5]
I tried using this module on my shop and got a 403 error

**Comment by L3o-pold** [comment]
Step to reproduce? 
Logs from your server?

**Comment by omeco4christ** [comment]
I just downloaded it from here and uploaded it and got that error

**Comment by L3o-pold** [comment]
Yeah that's great but I will need more information about your environment, Prestashop version, module version, logs from your server etc etc
